package ir.ronad.courierManager.dto.commonEvent.type;

/**
 * The UserRole enumeration.
 */
public enum UserRole {
    RONAD_ADMIN,
    MARKETING_MANAGER, MARKETING_EXPERT,
    OPERATIONS_MANAGER, OPERATIONS_EXPERT,
    SUPPORT_MANAGER, SUPPORT_EXPERT,
    WAREHOUSE_SUPERVISOR, WAREHOUSE_ADMIN, WAREHOUSE_OPERATOR,
    PARTNER_ADMIN, AGENCY_ADMIN, CENTER_ADMIN, SELLER_ADMIN, EXCHANGE_ADMIN,
    DRIVER,
    LOGISTICS_ADMIN,
    FINANCIAL_SUPERVISOR,
    NONE
}
